// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVehEP3C2r5Ze50BGzTezrq1Z8SFdPQVo',
    appId: '1:1011995366836:android:f009026873c90615174ee1',
    messagingSenderId: '1011995366836',
    projectId: 'biometricauth-5531f',
    databaseURL: 'https://biometricauth-5531f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'biometricauth-5531f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOqD_r9fMOi8alBfSfsM1AhTR8e8I1xSY',
    appId: '1:1011995366836:ios:5c69166d617f403f174ee1',
    messagingSenderId: '1011995366836',
    projectId: 'biometricauth-5531f',
    databaseURL: 'https://biometricauth-5531f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'biometricauth-5531f.firebasestorage.app',
    iosBundleId: 'com.example.h8FliBiometricStarter',
  );

}